#! /bin/sh

if test $(id -u) -ne 0; then
    echo "Probajte: sudo $0"
    exit 2
fi

himage FW hostname > /dev/null 2>&1
if test $? -ne 0; then
    echo "Experiment nije pokrenut (ili je pokrenut vise puta)."
    echo "cleanupAll && imunes NETWORK.imn &"
    exit 2
fi

for f in FW.sh FW_int.sh; do
    nft --check -f $f
    if test $? -ne 0; then
        exit 1
    fi
done

hcp FW.sh FW:
himage FW ./FW.sh

hcp FW_int.sh FW_int:
himage FW_int ./FW_int.sh
