#! /bin/sh

if test $(id -u) -ne 0; then
    echo "Probajte: sudo $0"
    exit 2
fi

himage FW hostname > /dev/null 2>&1
if test $? -ne 0; then
    echo "Experiment nije pokrenut (ili je pokrenut vise puta)."
    echo "cleanupAll && imunes NETWORK.imn &"
    exit 2
fi

. /home/student/imunes-examples/common/start_functions.sh

for net in 192.0.2.0 198.51.100.0
do
    netstat -rn | fgrep -q $net
    if test $? -ne 0; then
        route add -net ${net}/24 gw 203.0.113.1
    fi
done

http_servers="web"

if test $# -eq 1; then
    eid=$1
else
    for i in $http_servers
    do
        eid=`himage -e $i`
        if test $? -ne 0 ;then
            echo "Cannot find node $i"
            exit 2
        fi
    done
fi

if test $# -eq 1; then
    eid=$1
    isEidRunning $eid
else
    eid=`isNodeRunning web`
    if [ $? -ne 0 ]; then
	exit 1
    fi
fi

for serv in $http_servers
do
    echo "Starting http server on $serv..."
    h=${serv}@${eid}
    himage $h killall -q lighttpd
    himage $h mkdir -p /usr/local/etc/lighttpd
    himage $h mkdir -p /var/log/lighttpd
    himage $h chown -R www-data:www-data /var/log/lighttpd

    hcp WEB_files/${serv}.lighttpd.conf $h:/usr/local/etc/lighttpd/lighttpd.conf
    himage $h chmod 755 /usr/local/etc/lighttpd/lighttpd.conf
    hcp WEB_files/www.${serv}/* $h:/var/www/html/
    himage -b $h lighttpd -f /usr/local/etc/lighttpd/lighttpd.conf
done

