#! /bin/sh

if test $(id -u) -ne 0; then
    echo "Probajte: sudo $0"
    exit 2
fi

himage FW hostname > /dev/null 2>&1
if test $? -ne 0; then
    echo "Experiment nije pokrenut (ili je pokrenut vise puta)."
    echo "cleanupAll && imunes NETWORK.imn &"
    exit 2
fi

hcp FW.sh FW:
himage FW ./FW.sh

hcp FW_int.sh FW_int:
himage FW_int ./FW_int.sh
