[wokwi]
version = "1.0.0"
firmware = ".pio/build/esp32dev/firmware.bin"
elf = ".pio/build/esp32dev/firmware.elf"

[project]
name = "Lab3 RTC"
description = "RTC I2C connection"

[dependencies]
framework = "espidf"
platform = "espressif32"
board = "esp32dev"

[simulation]
diagram = "diagram.json"