{
 "title": "Elastic dashboard",
 "description": "Dashboard from elasticsearch database",
 "time": { "from": "now-6M", "to": "now" },
 "panels": [
  {
   "title": "Trenutni broj veza",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "fields.zeek_type:conn",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Distribucija protokola",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "proto.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "fields.zeek_type:conn",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Upozorenja",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "50" }, "type": "raw_data" }
     ],
     "query": "fields.zeek_type:notice",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Najpopularnija odredišta",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "id.resp_h.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "fields.zeek_type:conn AND NOT id.resp_h:(\\\"8.8.8.8\\\" OR \\\"8.8.4.4\\\" OR \\\"216.239.32.223\\\" OR \\\"239.255.255.250\\\")",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Timeline upozorenja",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "src.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "fields.zeek_type:notice",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Najpopularniji izvori",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "id.orig_h.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "fields.zeek_type:conn",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Sumnjive veze",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "conn_state.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      {
       "field": "id.orig_h.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "20" },
       "type": "terms"
      },
      {
       "field": "id.resp_h.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "20" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "fields.zeek_type:conn AND NOT conn_state:\\\"SF\\\"",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}