{
 "title": "Diplomski rad",
 "description": "Dashboard for connections",
 "time": { "from": "now-6M", "to": "now" },
 "panels": [
  {
   "title": "Veze po minuti",
   "type": "stat",
   "description": "Prikaz broja veza svaku minutu",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"zeek-logs\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"zeek_conn\")\n  |> filter(fn: (r) => r._field == \"uid\")\n  |> drop(columns: [\"src_ip\", \"dst_ip\", \"proto\", \"service\", \"conn_state\"])\n  |> aggregateWindow(every: 1m, fn: count, createEmpty: false)\n  |> yield(name: \"connections_per_minute\")"
    }
   ]
  },
  {
   "title": "Distribucija protokola",
   "type": "piechart",
   "description": "Omjer protokola u danom vremenskom intervalu",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"zeek-logs\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"zeek_conn\")\n  |> filter(fn: (r) => r._field == \"dst_port\")\n  |> filter(fn: (r) => r.proto != \"\")\n  |> group(columns: [\"proto\"])\n  |> count()\n  |> yield(name: \"protocol_distribution\")"
    }
   ]
  },
  {
   "title": "Upozorenja",
   "type": "table",
   "description": "Upozorenja iz zeek_logs/notice.log",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"zeek-logs\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"zeek_notice\")\n  |> filter(fn: (r) => r._field == \"message\")\n  |> group()\n  |> sort(columns: [\"_time\"], desc: true)\n  |> limit(n: 50)\n  |> keep(columns: [\"_time\", \"_value\", \"src_ip\", \"notice_type\"])\n  |> rename(columns: {_value: \"Upozorenje\", src_ip: \"Izvor\", notice_type: \"Tip\"})\n  |> yield(name: \"security_alerts\")"
    }
   ]
  },
  {
   "title": "Najpopularnija odredišta",
   "type": "bargauge",
   "description": "Prikaz komunikacije prema najčešćem odredištu",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"zeek-logs\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"zeek_conn\")\n  |> filter(fn: (r) => r.dst_ip != \"\")\n  |> filter(fn: (r) => r.dst_ip != \"239.255.255.250\" and r.dst_ip != \"216.239.32.223\" and r.dst_ip != \"8.8.8.8\" and r.dst_ip != \"8.8.4.4\")\n  |> group(columns: [\"dst_ip\"])\n  |> count()\n  |> group()\n  |> sort(columns: [\"_value\"], desc: true)\n  |> limit(n: 10)\n  |> yield(name: \"top_destinations\")"
    }
   ]
  },
  {
   "title": "Sumnjive veze",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"zeek-logs\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"zeek_conn\")\n  |> filter(fn: (r) => r._field == \"dst_port\")\n  |> filter(fn: (r) => r.conn_state != \"SF\" and r.conn_state != \"\")\n  |> group(columns: [\"conn_state\", \"src_ip\"])\n  |> count()\n  |> group()\n  |> sort(columns: [\"conn_state\", \"_value\"], desc: true)\n  |> rename(columns: {_value: \"count\"})\n  |> yield(name: \"suspicious_connections\")"
    }
   ]
  },
  {
   "title": "Najpopularniji izvori",
   "type": "bargauge",
   "description": "Prikaz izvora paketa (Iz mreže prema internetu) bez NAT-a",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"zeek-logs\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"zeek_conn\")\n  |> filter(fn: (r) => r.src_ip != \"\")\n  |> group(columns: [\"src_ip\"])\n  |> count()\n  |> group()\n  |> sort(columns: [\"_value\"], desc: true)\n  |> limit(n: 10)\n  |> yield(name: \"top_sources\")"
    }
   ]
  },
  {
   "title": "Timeline upozorenja",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"zeek-logs\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"zeek_notice\")\n  |> filter(fn: (r) => r._field == \"message\")\n  |> aggregateWindow(every: 5m, fn: count, createEmpty: false)\n  |> yield(name: \"alerts_timeline\")"
    }
   ]
  }
 ]
}