apiVersion: 1

datasources:
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "zeek-*"
    isDefault: true
    jsonData:
      esVersion: "8.17.0"
      timeField: "@timestamp"
      logMessageField: "message"
      logLevelField: "notice_type"
      interval: Daily
    version: 1
    editable: false
